# -*- coding: utf-8 -*-
"""CIE1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9CnEa2HMMmcrSQE6NNT1WAGRMGGdV6E
"""

import pandas as pd
a=pd.Series([1,2,3,4,5])
b=pd.Series([2,4,6,8,10])
result=a[~a.isin(b)]
result1=b[~b.isin(a)]
print(result)
print(result1)

import pandas as pd
data=pd.read_csv("/content/mtcars.csv")
print(data)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/mtcars.csv")
sns.histplot(data['mpg'],bins=10,color='blue',alpha=0.7)
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.title('Histogram of mpg')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/mtcars.csv")
sns.scatterplot(x='mpg',y='disp',data=data)
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.title('scatter of mpg')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/mtcars.csv")
sns.scatterplot(x='mpg',y='wt',data=data)
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.title('scatter of mpg')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/mtcars.csv")
sns.barplot(x='mpg',y='disp',data=data)
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.title('bar of mpg')
plt.show()